### ISSUE TITLE
Hot reload is not working

### ISSUE THREAD

**Issue by yuhao-nyc** [ReinBentdal/division#55]
Not sure if I miss something. But hot reload is not working for me. for example. changing `..textColor(Colors.black)` 
and save. Nothing happens to the UI. I need to reload manually

**Comment by 0Vipin0** [comment]
I am too facing the same problem, I have to restart app to see the changes. Hot Reload doesn't work, Every time, I have to Hot restart the app to see the changes in the app.

**Comment by ReinBentdal** [comment]
Hot-reload does not reload final variables outside the build method. This is not an issue with Division but has to do with how hot-reload works. You can read more about and how to overcome the issue here: https://flutter.dev/docs/development/tools/hot-reload#recent-code-change-is-included-but-app-state-is-excluded
